version: "2"

services:

  eureka-peer1:
    build:
      context: ../eureka-server-example
    image: eureka-server-tpd
    container_name: eureka-peer1
    environment:
      - SPRING_PROFILES_ACTIVE=peer1
      - LOGGING_LEVEL_COM_NETFLIX_DISCOVERY=DEBUG
    ports:
      - "8761:8761"
    networks:
      - network-eureka

  eureka-peer2:
    build:
      context: ../eureka-server-example
    image: eureka-server-tpd
    container_name: eureka-peer2
    environment:
      - SPRING_PROFILES_ACTIVE=peer2
      - LOGGING_LEVEL_COM_NETFLIX_DISCOVERY=DEBUG
    ports:
      - "8762:8762"
    networks:
      - network-eureka

  client-spanish:
    build:
      context: ../eureka-client
    image: eureka-client-tpd
    container_name: client-spanish
    environment:
      - SPRING_PROFILES_ACTIVE=spanish
      - LOGGING_LEVEL_COM_NETFLIX_DISCOVERY=DEBUG
    ports:
      - "8084:8084"
    networks:
      - network-eureka

  client-english:
    build:
      context: ../eureka-client
    image: eureka-client-tpd
    container_name: client-english
    environment:
      - SPRING_PROFILES_ACTIVE=english
      - LOGGING_LEVEL_COM_NETFLIX_DISCOVERY=DEBUG
    ports:
      - "8085:8085"
    networks:
      - network-eureka

networks:
  network-eureka:
